//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class МедицинскаяЛабораторияEntities : DbContext
    {
        public МедицинскаяЛабораторияEntities()
            : base("name=МедицинскаяЛабораторияEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Анализаторы> Анализаторы { get; set; }
        public virtual DbSet<Блокировки> Блокировки { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<ИсторияВходов> ИсторияВходов { get; set; }
        public virtual DbSet<Пациенты> Пациенты { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<СтраховыеКомпании> СтраховыеКомпании { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
        public virtual DbSet<УслугиВЗаказе> УслугиВЗаказе { get; set; }
    }
}
