//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Анализаторы
    {
        public int id { get; set; }
        public string название { get; set; }
        public string производитель { get; set; }
        public string модель { get; set; }
        public Nullable<System.DateTime> дата_ввода_в_эксплуатацию { get; set; }
        public Nullable<System.DateTime> дата_последней_поверки { get; set; }
    }
}
