//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Блокировки
    {
        public int id { get; set; }
        public Nullable<int> id_пользователя { get; set; }
        public string ip_адрес { get; set; }
        public Nullable<System.DateTime> время_начала { get; set; }
        public Nullable<int> длительность_минуты { get; set; }
        public string причина { get; set; }
        public Nullable<System.DateTime> дата_окончания { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
