//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.УслугиВЗаказе = new HashSet<УслугиВЗаказе>();
        }
    
        public int id { get; set; }
        public int id_пациента { get; set; }
        public string штрих_код { get; set; }
        public Nullable<System.DateTime> дата_создания { get; set; }
        public string статус { get; set; }
        public Nullable<bool> в_архиве { get; set; }
        public Nullable<System.DateTime> дата_закрытия { get; set; }
        public Nullable<int> id_врача { get; set; }
        public string комментарий { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пациенты Пациенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УслугиВЗаказе> УслугиВЗаказе { get; set; }
    }
}
