//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторияВходов
    {
        public int id { get; set; }
        public Nullable<int> id_пользователя { get; set; }
        public Nullable<System.DateTime> время_попытки { get; set; }
        public bool успешна { get; set; }
        public string ip_адрес { get; set; }
        public Nullable<bool> captcha_использована { get; set; }
        public string userAgent { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
