//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пациенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пациенты()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int id { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public System.DateTime дата_рождения { get; set; }
        public string серия_паспорта { get; set; }
        public string номер_паспорта { get; set; }
        public string телефон { get; set; }
        public string email { get; set; }
        public string номер_полиса { get; set; }
        public string тип_полиса { get; set; }
        public Nullable<int> id_страховой_компании { get; set; }
        public Nullable<System.DateTime> дата_регистрации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
        public virtual СтраховыеКомпании СтраховыеКомпании { get; set; }
    }
}
