//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.Блокировки = new HashSet<Блокировки>();
            this.Заказы = new HashSet<Заказы>();
            this.ИсторияВходов = new HashSet<ИсторияВходов>();
            this.УслугиВЗаказе = new HashSet<УслугиВЗаказе>();
        }
    
        public int id { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public byte[] фото { get; set; }
        public int id_роли { get; set; }
        public Nullable<System.DateTime> последний_вход { get; set; }
        public Nullable<bool> активен { get; set; }
        public Nullable<System.DateTime> дата_создания { get; set; }
        public Nullable<System.DateTime> дата_изменения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Блокировки> Блокировки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИсторияВходов> ИсторияВходов { get; set; }
        public virtual Роли Роли { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УслугиВЗаказе> УслугиВЗаказе { get; set; }
    }
}
