//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Услуги()
        {
            this.УслугиВЗаказе = new HashSet<УслугиВЗаказе>();
        }
    
        public int код { get; set; }
        public string наименование { get; set; }
        public decimal стоимость { get; set; }
        public Nullable<int> срок_выполнения { get; set; }
        public Nullable<decimal> среднее_отклонение { get; set; }
        public string описание { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УслугиВЗаказе> УслугиВЗаказе { get; set; }
    }
}
