//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlaaab
{
    using System;
    using System.Collections.Generic;
    
    public partial class УслугиВЗаказе
    {
        public int id { get; set; }
        public int id_заказа { get; set; }
        public int код_услуги { get; set; }
        public string статус { get; set; }
        public Nullable<System.DateTime> дата_выполнения { get; set; }
        public Nullable<int> id_лаборанта { get; set; }
        public Nullable<int> id_анализатора { get; set; }
        public string результат { get; set; }
        public Nullable<System.DateTime> дата_назначения { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
